# vim:sw=2:ts=2
# action name
name: 'phoenix-build'

# action author
author: 'Marek Białowąs <marek.bialowas@phoenix-rtos.com>'

# action description
description: 'Builds Phoenix-RTOS based projects'

# action input values
inputs:
  target:
    description: 'Target env variable'
    default: 'ia32-generic-qemu'
    required: false
  syspage:
    description: 'Syspage env variable'
    default: ''
    required: false
  params:
    description: 'All parameters to the main build script - as string'
    required: true
  buildroot:
    description: 'Custom phoenix-rtos-project buildroot (relative path)'
    default: ''
    required: false
  nightly:
    description: 'Build additional tests'
    default: false
    required: false

# action runner
runs:
  using: 'docker'
  image: 'docker://lukileczo/phoenix-build'
  env:
    CONSOLE: 'serial'
    DEBUG: '1'
    TARGET: ${{ inputs.target }}
    SYSPAGE: ${{ inputs.syspage }}
    CI_CUSTOM_BUILDROOT: ${{ inputs.buildroot }}
    LONG_TEST: ${{ inputs.nightly == 'true' && 'y' || 'n' }}
  args:
    - ${{ inputs.params }}  # note: params will be split by build.sh internally

# branding
branding:
  icon: terminal
  color: green
