#!/bin/busybox sh

export PATH=/bin:/usr/bin

# mount RAM disks
mkdir -p /var/log /var/run /var/cfg /var/cfg-req /var/tmp /var/login /var/users-req

# Create directories if local is empty
if [ ! -d /local/etc ]; then
	mkdir /local/etc
fi
if [ ! -d /local/etc/rc.conf.d ]; then
	mkdir /local/etc/rc.conf.d
fi

# RTC has failed, set last "build" date
# sleep 1
# TIMESTAMP_FILE="/bin/ash"
# if [ "$(date +%s)" -lt 1446055000 ] && [ -f "$TIMESTAMP_FILE" ]; then
#     date -s "@$(date -r $TIMESTAMP_FILE +%s)" > /dev/null
#     #hwclock -w
# fi

# custom (per-project, per-customer initialization)
if [ -f /etc/rc.local ]; then
    /etc/rc.local
fi
