# vim:sw=2:ts=2
# static linters which can be run in a single repo (do not need phoenix-rtos-project)
name: lint

# on events
on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'
  workflow_call:  # reusable workflow - the same jobs in submodules

jobs:
  # reviewdog: use clang-format for PR review
  clang-format-pr:
    if: github.event_name == 'pull_request'
    name: clang-format-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # current PR merge commit + 1 back

      - run: git diff -U0 HEAD^ | clang-format-diff-10 -p1 | patch -p0
      - name: clang-format-diff
        uses: reviewdog/action-suggester@v1
        with:
            tool_name: clang-format-diff
            fail_on_error: true


  # reviewdog: codespell for PRs only
  codespell-pr:
    if: github.event_name == 'pull_request'
    name: codespell-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # current PR merge commit + 1 back

      - name: codespell
        uses: nalajcie/action-codespell@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review


  # reviewdog: shellcheck
  shellcheck-pr:
    if: github.event_name == 'pull_request'
    name: shellcheck-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
